function [ outputMesh ] = rotateMesh( mesh,rot,axis )

if(axis=='x')
    A = [0 0 1 0; ...
        cosd(rot) sind(rot) 0 0; ...
        -sind(rot) cosd(rot) 0 0; ...
        0 0 0 1];
elseif(axis=='y')
    A = [cosd(rot) 0 -sind(rot)  0; ...
        0 1 0  0; ...
        sind(rot) 0 cosd(rot)  0; ...
        0 0 0 1];
elseif(axis=='z')
    A = [cosd(rot) sind(rot) 0 0; ...
        -sind(rot) cosd(rot) 0 0; ...
        0 0 1 0; ...
        0 0 0 1];
else
    A = [cosd(rot) -sind(rot) 0 0; ...
        sind(rot) cosd(rot) 0 0; ...
        0 0 1 0; ...
        0 0 0 1];
end

%If axis is unspecified, model is rotated around z axis

tform = affine3d(A);

outputMesh = pctransform(mesh,tform);

end

